POST http://localhost:9000/api/signup
Content-Type: application/json

{
    "fullname" : "dhruv",
    "email" : "admin@gmail.com",
    "password" : "1234"
}
###

POST http://localhost:9000/api/login
Content-Type: application/json

{
    "email" : "admin@gmail.com",
    "password" : "1234",
    "is_staff" : 1
}
###
POST http://localhost:9000/api/login
Content-Type: application/json

{
    "email" : "dhruv@gmail.com",
    "password" : "12345"
}

###

POST http://localhost:9000/api/contact
Content-Type: application/json

{
    "name":"dhruvv",
    "email":"aadmin@gmail.com",
    "message":"hello how are you"
}

###
POST http://localhost:9000/api/addCategory
Content-Type: application/json

{
    "title":"Menss Wear",
    "image":"https://rukminim1.flixcart.com/image/800/960/jvv9zm80/kids-ethnic-set/b/v/t/2-3-years-digibc001-digimart-original-imafggkydgvztb2k.jpeg?q=50",
    "status":1,
    "feature_to_home":1,
    "link":"https://www.amazon.in/b?_encoding=UTF8&tag=zoddok-21&linkCode=ur2&linkId=0bad38f96902e04fd811ae1a541a8d8a&camp=3638&creative=24630&node=1968024031"
}

###
POST http://localhost:9000/api/addProduct
Content-Type: application/json

{
    "flipkart_link":"//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ac&ref=tf_til&ad_type=product_link&tracking_id=zoddok-21&marketplace=amazon&amp;region=IN&placement=B076CW8XDJ&asins=B076CW8XDJ&linkId=480cfcdf461276e6cfcc38a61ba53ef1&show_border=true&link_opens_in_new_window=true&price_color=333333&title_color=060d14&bg_color=ffffff",
    "status":1,
    "category":"Mens Wear",
    "feature_to_home":1,
    "name":"Shirt"
}

###
GET  http://localhost:9000/api/showCategory
Content-Type: application/json

###
GET http://localhost:9000/api/showCategoryAdmin
Content-Type: application/json

###
GET http://localhost:9000/api/showCategorylistAdmin
Content-Type: application/json

###
GET  http://localhost:9000/api/showAllCategory
Content-Type: application/json

###
GET http://localhost:9000/api/showProduct
Content-Type: application/json

###
GET http://localhost:9000/api/showAllProduct
Content-Type: application/json

###
GET http://localhost:9000/api/showProductAdmin
Content-Type: application/json

###
DELETE http://localhost:9000/api/deleteProduct/25
Content-Type: application/json

###
DELETE http://localhost:9000/api/deleteCategory/25
Content-Type: application/json

###
PATCH http://localhost:9000/api/statusProduct/false/1
Content-Type: application/json

###
PATCH http://localhost:9000/api/updateCate/6064145d7c07e725401b16ee
Content-Type: application/json

{
    "title":"Music",
    "image":"https://images-na.ssl-images-amazon.com/images/I/71M5Y9eocIL._UY445_.jpg",
    "link":"https://www.amazon.in/b?_encoding=UTF8&tag=zoddok-21&linkCode=ur2&linkId=0bad38f96902e04fd811ae1a541a8d8a&camp=3638&creative=24630&node=1968024031"
}

###
PATCH http://localhost:9000/api/statusCategory/false/1
Content-Type: application/json

###
GET http://localhost:9000/api/users
Content-Type: application/json

###
GET http://localhost:9000/api/feedback
Content-Type: application/json

###
GET http://localhost:9000/api/totalrecord
Content-Type: application/json