POST http://localhost:9000/api/signup
Content-Type: application/json

{
    "fullname" : "dhruv",
    "email" : "admin@gmail.com",
    "password" : "1234"
}
###

POST http://localhost:9000/api/login
Content-Type: application/json

{
    "email" : "admin@gmail.com",
    "password" : "1234"
}
###

POST http://localhost:9000/api/contact
Content-Type: application/json

{
    "name":"dhruvv",
    "email":"aadmin@gmail.com",
    "message":"hello how are you"
}

###
POST http://localhost:9000/api/addCategory
Content-Type: application/json

{
    "title":"Mens Wear",
    "image":"https://rukminim1.flixcart.com/image/800/960/jvv9zm80/kids-ethnic-set/b/v/t/2-3-years-digibc001-digimart-original-imafggkydgvztb2k.jpeg?q=50",
    "status":1,
    "feature_to_home":1,
    "link":"https://www.amazon.in/b?_encoding=UTF8&tag=zoddok-21&linkCode=ur2&linkId=0bad38f96902e04fd811ae1a541a8d8a&camp=3638&creative=24630&node=1968024031"
}

###
POST http://localhost:9000/api/addProduct
Content-Type: application/json

{
    "flipkart_link":"//ws-in.amazon-adsystem.com/widgets/q?ServiceVersion=20070822&OneJS=1&Operation=GetAdHtml&MarketPlace=IN&source=ss&ref=as_ss_li_til&ad_type=product_link&tracking_id=zoddok-21&marketplace=amazon&region=IN&placement=B08R1PRPXS&asins=B08R1PRPXS&linkId=0612b96e4e4e513a2735e6be527a4240&show_border=true&link_opens_in_new_window=true",
    "status":1,
    "category":"Kids Wear",
    "feature_to_home":1,
    "name":"Shirt"
}

###
GET  http://localhost:9000/api/showCategory
Content-Type: application/json

###
GET  http://localhost:9000/api/showAllCategory
Content-Type: application/json

###
GET http://localhost:9000/api/showProduct
Content-Type: application/json

###
GET http://localhost:9000/api/showAllProduct
Content-Type: application/json